'use client'

import { useEffect, useState } from 'react'
import { useSession } from 'next-auth/react'
import { useRouter } from 'next/navigation'
import { AppLayout } from '@/components/AppLayout'
import { BookOpen, MessageCircle, TrendingUp, Zap, Shield } from 'lucide-react'
import { motion } from 'framer-motion'

const TELEGRAM_SUPPORT = 'https://t.me/your-support-group' // Replace with actual Telegram group

const articles = [
  {
    id: 1,
    title: 'How Does the Bot Generate Profit?',
    content: `Our trading bot takes advantage of price differences between OKX and Binance.

Every two hours, it analyzes the market automatically.

When the price difference between the two exchanges exceeds 3%, the system executes an instant buy/sell trade.

The bot uses only 10% of each user's balance per trade, minimizing risk during market fluctuations.

Each operation is completed in under 50 milliseconds (0.05 seconds).

After each trade, the profits are distributed equally (3%) among all active users.

A small remaining portion is reserved by the system for bot development and team salaries, ensuring continuous and sustainable platform growth.`,
  },
  {
    id: 2,
    title: 'Getting Started Guide',
    content: `1. Register an account or sign in
2. Deposit USDT to your wallet
3. Purchase a trading bot (minimum 5 USDT)
4. The bot will start trading automatically every 2 hours
5. Monitor your profits on the dashboard
6. Withdraw your earnings anytime`,
  },
  {
    id: 3,
    title: 'Understanding Profit Rates',
    content: `Profit rates are calculated based on your account balance. Higher balances generate higher daily profits.

The bot executes 12 trades per day (every 2 hours), and your daily profit is the sum of all trades.

Your balance determines your profit tier. As your balance grows through profits, you automatically move to higher profit tiers.`,
  },
  {
    id: 4,
    title: 'Referral System Explained',
    content: `Earn passive income through our referral system:

• 5% Instant Commission: When someone uses your referral code and deposits, you instantly earn 5% of their deposit.

• 20% Profit Commission: You also earn 20% of all future profits generated by users you referred. This is ongoing passive income!

Share your referral code with friends and start earning today!`,
  },
]

export default function InfoPage() {
  const { data: session, status } = useSession()
  const router = useRouter()
  const [expandedArticle, setExpandedArticle] = useState<number | null>(null)

  useEffect(() => {
    if (status === 'unauthenticated') {
      router.push('/login')
      return
    }
  }, [status, router])

  if (status === 'loading') {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">Loading...</p>
        </div>
      </div>
    )
  }

  return (
    <AppLayout>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        className="space-y-6"
      >
        <div className="card text-center">
          <BookOpen size={48} className="mx-auto mb-4 text-primary-600" />
          <h2 className="text-2xl font-bold mb-2">Information & Support</h2>
          <p className="text-gray-600">
            Learn how our platform works and get support
          </p>
        </div>

        <div className="card">
          <div className="flex items-center gap-3 mb-4">
            <MessageCircle className="text-blue-600" size={24} />
            <h3 className="text-xl font-semibold">Support</h3>
          </div>
          <p className="text-gray-600 mb-4">
            Need help? Join our Telegram support group for assistance.
          </p>
          <a
            href={TELEGRAM_SUPPORT}
            target="_blank"
            rel="noopener noreferrer"
            className="btn-primary w-full inline-block text-center"
          >
            Join Telegram Support
          </a>
        </div>

        <div className="card">
          <h3 className="font-semibold text-lg mb-4">Articles & Guides</h3>
          <div className="space-y-3">
            {articles.map((article) => (
              <div
                key={article.id}
                className="border border-gray-200 rounded-lg overflow-hidden"
              >
                <button
                  onClick={() =>
                    setExpandedArticle(
                      expandedArticle === article.id ? null : article.id
                    )
                  }
                  className="w-full text-left p-4 hover:bg-gray-50 transition-colors"
                >
                  <div className="flex items-center justify-between">
                    <h4 className="font-semibold">{article.title}</h4>
                    <span className="text-gray-400">
                      {expandedArticle === article.id ? '−' : '+'}
                    </span>
                  </div>
                </button>
                {expandedArticle === article.id && (
                  <motion.div
                    initial={{ height: 0 }}
                    animate={{ height: 'auto' }}
                    exit={{ height: 0 }}
                    className="overflow-hidden"
                  >
                    <div className="p-4 pt-0 text-gray-700 whitespace-pre-line">
                      {article.content}
                    </div>
                  </motion.div>
                )}
              </div>
            ))}
          </div>
        </div>

        <div className="card bg-gradient-to-br from-primary-50 to-primary-100 border border-primary-200">
          <div className="flex items-start gap-3">
            <Shield size={24} className="text-primary-600 mt-1 flex-shrink-0" />
            <div>
              <h3 className="font-semibold text-lg mb-2 text-primary-900">
                Security & Safety
              </h3>
              <p className="text-sm text-primary-800">
                Our platform uses advanced security measures to protect your funds. 
                All transactions are encrypted and your data is stored securely. 
                The trading bot uses only 10% of your balance per trade to minimize risk.
              </p>
            </div>
          </div>
        </div>

        <div className="card">
          <h3 className="font-semibold text-lg mb-4">Key Features</h3>
          <div className="grid grid-cols-2 gap-4">
            <div className="text-center p-4 bg-gray-50 rounded-lg">
              <Zap size={32} className="mx-auto mb-2 text-yellow-500" />
              <p className="font-medium text-sm">Fast Trades</p>
              <p className="text-xs text-gray-600 mt-1">
                Completed in under 50ms
              </p>
            </div>
            <div className="text-center p-4 bg-gray-50 rounded-lg">
              <TrendingUp size={32} className="mx-auto mb-2 text-green-500" />
              <p className="font-medium text-sm">Automated</p>
              <p className="text-xs text-gray-600 mt-1">
                Trades every 2 hours
              </p>
            </div>
            <div className="text-center p-4 bg-gray-50 rounded-lg">
              <Shield size={32} className="mx-auto mb-2 text-blue-500" />
              <p className="font-medium text-sm">Low Risk</p>
              <p className="text-xs text-gray-600 mt-1">
                Only 10% per trade
              </p>
            </div>
            <div className="text-center p-4 bg-gray-50 rounded-lg">
              <MessageCircle size={32} className="mx-auto mb-2 text-purple-500" />
              <p className="font-medium text-sm">24/7 Support</p>
              <p className="text-xs text-gray-600 mt-1">
                Telegram available
              </p>
            </div>
          </div>
        </div>
      </motion.div>
    </AppLayout>
  )
}
